// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectLeer.Data;

#nullable disable

namespace ProjectLeer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241129085438_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LeerlingVak", b =>
                {
                    b.Property<int>("LeerlingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VakkenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LeerlingId", "VakkenId");

                    b.HasIndex("VakkenId");

                    b.ToTable("LeerlingVak");
                });

            modelBuilder.Entity("ProjectLeer.Entity.Leerkracht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Klassen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Leerkrachten");
                });

            modelBuilder.Entity("ProjectLeer.Entity.Leerling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Graad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Klas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Leerlingen");
                });

            modelBuilder.Entity("ProjectLeer.Entity.Vak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeerkrachtId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeerkrachtId");

                    b.ToTable("Vakken");
                });

            modelBuilder.Entity("LeerlingVak", b =>
                {
                    b.HasOne("ProjectLeer.Entity.Leerling", null)
                        .WithMany()
                        .HasForeignKey("LeerlingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectLeer.Entity.Vak", null)
                        .WithMany()
                        .HasForeignKey("VakkenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectLeer.Entity.Vak", b =>
                {
                    b.HasOne("ProjectLeer.Entity.Leerkracht", null)
                        .WithMany("Vakken")
                        .HasForeignKey("LeerkrachtId");
                });

            modelBuilder.Entity("ProjectLeer.Entity.Leerkracht", b =>
                {
                    b.Navigation("Vakken");
                });
#pragma warning restore 612, 618
        }
    }
}
